# Generated by Django 4.1 on 2022-10-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles')),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_type', models.CharField(choices=[('Regular', 'Regular'), ('Heated seats', 'Heated seats')], default='Regular', max_length=50)),
                ('transmission', models.CharField(choices=[('Manual Transmission', 'Manual Transmission'), ('Automatic', 'Automatic')], default='Manual Transmission', max_length=50)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('status', models.CharField(choices=[('After Returns', 'After Returns'), ('Before Returns', 'Before Returns')], default='After Returns', max_length=50)),
                ('after_returns', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vehicles')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vehicles')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
