# Generated by Django 4.1 on 2022-08-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_reviewrating_options_alter_vehicles_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='varient',
            new_name='vehicle',
        ),
    ]
