# Generated by Django 4.1 on 2022-09-03 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_vehicles_reg_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='vehicles/vehicleStatus')),
                ('status', models.CharField(choices=[('After Returns', 'After Returns'), ('Before Returns', 'Before Returns')], default='After Returns', max_length=50)),
                ('after_returns', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vehicles')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
