# Generated by Django 4.1 on 2022-09-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='reg_number',
        ),
    ]
