# Generated by Django 4.1 on 2022-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_rent_options_rent_created_at_rent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='reg_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
