# Generated by Django 4.1 on 2022-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_rent_down_payment_payment_rent_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Placed', 'Placed'), ('Piked', 'Piked'), ('Return', 'Return'), ('Canceled', 'Canceled')], default='New', max_length=20),
        ),
    ]
