# Generated by Django 4.1 on 2022-10-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0007_cars_reservation_is_payed_cars_reservation_status'),
        ('order', '0009_alter_rent_total_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rent.cars_reservation'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rent.cars'),
        ),
    ]
