# Generated by Django 4.1 on 2022-08-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='irst_name',
            new_name='first_name',
        ),
    ]
