# Generated by Django 4.1 on 2022-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/aadhar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_licence',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/drivinglicence'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/pancard'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_card_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
