# Generated by Django 4.1 on 2022-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('vender', 'vender'), ('Admin', 'Admin')], default='Customer', max_length=50),
        ),
    ]
