# Generated by Django 4.1 on 2022-09-15 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0006_alter_vendor_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('creator', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles')),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_type', models.CharField(choices=[('Regular', 'Regular'), ('Heated seats', 'Heated seats')], default='Regular', max_length=50)),
                ('transmission', models.CharField(choices=[('Manual Transmission', 'Manual Transmission'), ('Automatic', 'Automatic')], default='Manual Transmission', max_length=50)),
                ('description', models.TextField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('on_the_way', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_the_location', models.CharField(blank=True, max_length=255, null=True)),
                ('come_back', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cars_ARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.CharField(max_length=5)),
                ('id_location', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('code_registration', models.CharField(max_length=20)),
                ('creator_ARC', models.CharField(max_length=255)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('on_the_way', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_the_location', models.CharField(blank=True, max_length=255, null=True)),
                ('come_back', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=255)),
                ('supp_unique_var', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('client_document_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.CharField(max_length=255)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('creator_change', models.CharField(blank=True, max_length=64, null=True)),
                ('type_change', models.CharField(blank=True, max_length=64, null=True)),
                ('id_arc', models.CharField(blank=True, max_length=64, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carReservations', to='car_rent.cars')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationReservations', to='car_rent.locations')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Cars_Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('client_document_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('deposit', models.CharField(max_length=255)),
                ('deposit_currency', models.CharField(max_length=255)),
                ('deposit_is_active', models.BooleanField(default=False)),
                ('total_price', models.CharField(max_length=255)),
                ('total_price_currency', models.CharField(max_length=255)),
                ('total_price_is_paid', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carRents', to='car_rent.cars')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationRents', to='car_rent.locations')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='main_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='car_rent.locations'),
        ),
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
