# Generated by Django 4.1 on 2022-09-26 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0007_alter_vendor_owner'),
        ('car_rent', '0004_cars_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=10)),
                ('document', models.FileField(upload_to='vendor/vehicles/documents')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rent.cars')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
