# Generated by Django 4.1 on 2022-10-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0005_carsdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_reservation',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cars_reservation',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
