# Generated by Django 4.1 on 2022-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0006_cars_reservation_price_cars_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_reservation',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cars_reservation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Placed', 'Placed'), ('Piked', 'Piked'), ('Return', 'Return'), ('Canceled', 'Canceled')], default='New', max_length=20),
        ),
    ]
